### ISSUE TITLE
Pinch Gestures

### ISSUE THREAD

**Issue by boehm-e** [pmndrs/xr#132]
Hi,

I would like to implement pinch to zoom, 
Is it something possible with this lib ? Maybe with `useXREvent`

Thank you

**Comment by saitonakamura** [comment]
There's https://github.com/stewdio/handy.js

**Comment by boehm-e** [comment]
Thank you for your answer @saitonakamura 
I was not clear, I am looking for a way for a user to scale a 3d model by pinching the touch screen.
I do not see any events allowing me to do that withing this library (same for pmndrs/drei and react-three-fiber)

**Comment by AdaRoseCannon** [comment]
I need to record some pinch poses for that for people to use, if you do make some yourself please add them to the repo

**Comment by AdaRoseCannon** [comment]
for interactions on the 2D screen you can listen for selectstart events you can get the position of the finger in 3D space by getting the target Ray space position. 

if you get a selectstart then another before a selected then two fingers are down in this situation the user is pinching

**Comment by bbohlender** [comment]
With react-three/xr v6, pinching (which requires support for multiple pointers) works out of the box (in handheld AR but also in head worn AR and VR use cases) and uses the [pointer-events standard](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events). You can therefore implement pinch to zoom gesture just like [on html/css](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures).
