### ISSUE TITLE
Support Plane Detection API

### ISSUE THREAD

**Issue by richardanaya** [pmndrs/xr#204]
With Oculus Browser now supporting plane detection API, would be a nice feature to add.

This examples works and can be used as a reference: https://immersive-web.github.io/webxr-samples/proposals/plane-detection.html

**Comment by zob360** [comment]
Please where is the code? thanks!

**Comment by zob360** [comment]
This feature is very needed!

**Comment by Soham1803** [comment]
Can this be only implemented in Oculus devices or would work on other mobile devices too? As far as I know Web-XR supports plane detection, I expected react-xr to already have this feature. Is it simply a plane detection or am I misunderstanding something here?

**Comment by CodyJasonBennett** [comment]
It works for AR also. I've been working on upstreaming stuff to three.js, but this is feasible to implement here. https://github.com/mrdoob/three.js/pull/26098 recently moves it to user-land.

**Comment by Soham1803** [comment]
So, it means an android device with google arcore support will do the job, right? If its a `good-first-issue` and could be solved by a new developer, I would like to work on it.

**Comment by CodyJasonBennett** [comment]
Sure thing. Accompanying spec would be https://immersive-web.github.io/real-world-geometry/plane-detection.html and there's https://github.com/mrdoob/three.js/pull/26098 and https://github.com/mrdoob/three.js/pull/24855 for reference. I believe the former is broken since it's passing `XRPlaneSet` where the demo expects `XRFrame`, but the spec also includes a good example.

**Comment by Soham1803** [comment]
Hi @CodyJasonBennett, 
I was exploring the repo and found out some stuffs that might be useful. 

* While creating an XRButton we need to specify a string `"plane-detection"` in **requiredFeatures** array as an argument in the method **requestSession**. What I could understand is, in the following line of code, **optionalFeatures** are specified but **requiredFeatures** aren't, I don't know may be I'm misunderstanding something.
https://github.com/pmndrs/react-xr/blob/df017c8a2dbb9b603b163b97e5bdbc8b489e2a71/src/XR.tsx#L292

* We are generating **optionalFeatures** through this function below, then may be we need an another function to specify **requiredFeatures**.
https://github.com/pmndrs/react-xr/blob/df017c8a2dbb9b603b163b97e5bdbc8b489e2a71/src/XR.tsx#L264

Would this be a valid step? Please correct me if I'm wrong.
And my apologize if I'm being pretty slow with this, getting familiar with the repo.

**Comment by richardanaya** [comment]
This is supported in ThreeJS https://github.com/mrdoob/three.js/pull/24908 should be fairly easy to create some kind of components that spawns other components based on changes to detected planes :) 

<PlaneBuilder component={(plane)=> <BuildingWall plane={plane}/>} />

**Comment by bbohlender** [comment]
Supported in v6. See this [tutorial](https://docs.pmnd.rs/xr/tutorials/object-detection).
