### ISSUE TITLE
isHandTracking remaining false in AR session

### ISSUE THREAD

**Issue by rekliner** [pmndrs/xr#219]
@CodyJasonBennett, in reference to discussion #207  it appears that PR #208 did not fix the underlying issue.  isHandTracking is remaining false in AR sessions.  Here is a demonstration with the default pmndrs Hands example sandbox forked to call an AR session with the latest releases: https://ekc8wh.csb.app/ 

It has remained consistent across all other AR code utilizing hands I've tried.  Forcing the isHandTracking property has no effect.

**Comment by bbohlender** [comment]
In react-three/xr v6, checking whether hand tracking is active, can be done via

```
const isHandTracking = useXR(xr => xr.handStates.length > 0)
```

Feel free to reopen if this does not work.
