### ISSUE TITLE
First Person Controls inside VR mode

### ISSUE THREAD

**Issue by carolinaroqu3** [pmndrs/xr#222]
Is there any possibility to use the joystick controls of the glasses to move the camera and walk around the scene?

**Comment by snettah** [comment]
https://github.com/pmndrs/react-xr/issues/218 here

**Comment by rekliner** [comment]
@carolinaroqu3 as others pointed out useController() is what you are looking for.  For a working component you can drop in check out https://codesandbox.io/s/three-fiber-xr-headset-camera-bounds-box-tin2ko?file=/components/MovementController.js 

ofc there is al sorts of context on how you want movement to work in your personal project...factors like speed, gravity, collision, acceleration, tilt,...etc.  You will eventually be coding for your own solution. The sky is the limit, but this simple example should get you started for basic movement.

**Comment by abernier** [comment]
I think this issue can bd closed as it is solved by https://github.com/pmndrs/react-xr/issues/222#issuecomment-1343396191

**Comment by bbohlender** [comment]
Since the answer to this question has changed slightly in v6, I am linking to a [simple tutorial](https://docs.pmnd.rs/xr/tutorials/gamepad) that introduces how to implement locomotion for controlling the viewers position by controlling its origin.
