### ISSUE TITLE
[Question]: Disable ray through object

### ISSUE THREAD

**Issue by JenniferFalkenstein** [pmndrs/xr#225]
Hi there,

I have a Plane and a Cube (and light). The Cube is placed behind the Plane and is wrapped within an `<Interact />` Element, while the Plane doesn't do anything.
Every time the Cube gets selected it changes the color of the light into another color.

Now I noticed that even if the Plane is in front of the Cube, the ray still goes through the Plane and therefore is able to select the Cube behind, which is not what I want. The Plane should actually block the ray, so the player won't be able to click the Cube behind.

Is there some kind of prop I have to set or is there another way to accomplish this? 😄

**Comment by saitonakamura** [comment]
@JenniferFalkenstein events are triggered on first interactive target by default https://github.com/pmndrs/react-xr/blob/6a16dfa29a92420598e4bd433c8790b8e9c3f18a/src/Interactions.tsx#L68. Another option is to provide custom [events.filter](https://github.com/pmndrs/react-xr/blob/6a16dfa29a92420598e4bd433c8790b8e9c3f18a/src/Interactions.tsx#L68) function

So to block the Cube you'd either need to
* wrap Plane in Interactive component
* add event handlers to Plane via useInteraction
* provide your own logic via events.filter

**Comment by bbohlender** [comment]
The answer to this question has changed (and is more aligned with what developers know comming from html/css). Interactions in react-three/xr v6 now work just like in the whole react-three ecosystem, which means that the [pointer-events concept](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) is used. [Here's a tutorial](https://docs.pmnd.rs/xr/tutorials/interactions) that gives an overview what is possible with the new interactions system. For your use case, you can new use set `pointerEvents="auto"` on the plane that should capture the interaction and to prevent intersecting with objects behind that plane.
