### ISSUE TITLE
[Question]: How to implement anchors?

### ISSUE THREAD

**Issue by elibenjii** [pmndrs/xr#249]
Hey guys, is there a way to implement anchors? thanks awesome library!

https://github.com/immersive-web/webxr-samples/blob/main/hit-test-anchors.html

**Comment by netgfx** [comment]
This might work for you https://codesandbox.io/s/webxr-model-ru1k8z I have a mix of react-xr and plain-old webxr to implement anchors.

**Comment by bbohlender** [comment]
anchor api is now supported in 6.1 :)
