### ISSUE TITLE
Eye Control

### ISSUE THREAD

**Issue by seanaguinaga** [pmndrs/xr#270]
Is there a way to use Eye Control like this in Unity:

https://developer.oculus.com/documentation/unity/move-eye-tracking/

not sure if it is exposed as an api yet or not

**Comment by bbohlender** [comment]
react-three/xr v6 supports gaze input, but I am not sure if the Meta Quest Pro already exposes it to the browser, so I havent tested it yet. Feel free to reopen if it does not work
