### ISSUE TITLE
Encountered  two children with the same key when load controllers with <XR/> in Next.js

### ISSUE THREAD

**Issue by liyan827** [pmndrs/xr#271]
My Project structure:Next.js13+React18+@react-three-xr:5.4.1
My usage is as follows:
`<VRButton />
      <Canvas gl={{preserveDrawingBuffer: true}} {...props} onCreated={(state)=>{
        state.gl.setClearColor(0xebf2f7);
        state.gl.localClippingEnabled = true;
      }}>
        <XR>
          <directionalLight intensity={0.75} />
          <ambientLight intensity={0.75} />
          {children}
          <Preload all />
          <Controllers />
        </XR>
      </Canvas>`
Here is the error:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/124141374/234215437-adf0294f-b302-4739-9693-497446e448fd.png">
What could be the reason for this? Is it because React is re-rendering?thanks for the reply

**Comment by bbohlender** [comment]
should be resolved in v6. Feel free to reopen if something doesnt work.
Since you probably need to migrate from v5, here's the [migration guide](https://docs.pmnd.rs/xr/migration/from-react-three-xr-5).
