### ISSUE TITLE
XR Controllers disappear when using conditional rendering

### ISSUE THREAD

**Issue by netgfx** [pmndrs/xr#291]
Hello, I have this example https://codesandbox.io/s/react-xr-simple-demo-with-swap-6l8xzd?file=/src/index.tsx where I'm making a sphere geometry appear when a button is clicked via react conditional rendering. This action is making the Controllers (Oculus quest 2) disappear, although moving them around and squeezing will emit events and interact, I believe only the 3D models aren't visible.

If the session is somehow restarted (taking off the headset and on again) will make the Controllers appear again.

Not sure if this is a known issue or if my implementation is somehow faulted.

**Comment by netgfx** [comment]
narrowing it down, it seems that when the `useLoader` or `useTexture` is used (even if the result doesn't get used) the Controllers are disappearing.

**Comment by CodyJasonBennett** [comment]
Is this still an issue with [v5.6.2](https://github.com/pmndrs/react-xr/releases/tag/v5.6.2)?

**Comment by eigilnikolajsen** [comment]
I'm still having this issue in version 5.7.0
When previewing in Meta Quest Browser the controllers dissappear when loading a video texture. If I exit and reenter the VR experience the controllers show up again.

**Comment by chriskch** [comment]
Are there any news on that?

**Comment by CodyJasonBennett** [comment]
From Discord, looks like state is not being created correctly when `XR` remount.

**Comment by MirkoCzo** [comment]
> From Discord, looks like state is not being created correctly when `XR` remounts.

Hi, is there any way around this problem?

**Comment by MP242** [comment]
Hello! Is the problem still unresolved?

**Comment by bbohlender** [comment]
@MP242 @MirkoCzo @chriskch @eigilnikolajsen  should be resolved in v6. Feel free to reopen if something doesnt work.
Since you probably need to migrate from v5, here's the [migration guide](https://docs.pmnd.rs/xr/migration/from-react-three-xr-5).
