### ISSUE TITLE
Give a better message when not on HTTPS

### ISSUE THREAD

**Issue by richardanaya** [pmndrs/xr#301]
This might be confusing to new users who don't know they need to run their dev servers on HTTPS.

**Comment by CodyJasonBennett** [comment]
I believe we already discern HTTPS, but would be good to link to instructions in any case.

https://github.com/pmndrs/react-xr/blob/4d23eb88daa5ae484de05fa157cdc7fe366c2e47/src/XR.tsx#L327-L345

**Comment by bbohlender** [comment]
imo this shouldn't be part of the implementation but rather be mentioned in the tutorials on the documentation
