### ISSUE TITLE
iOS support?

### ISSUE THREAD

**Issue by dendrofen** [pmndrs/xr#302]
Note: I'm using code example from README.

### Critical things

1. There are some critical issues in current version, connected to ability to run AR sessions on android devices event with support available from "can i use" website...

2. There are old pull requests in current repository which is not merged

3. There are very old (almost 1-2 year) issues without answers or still open

4. No workaround for ios devices

### Possible solutions
- add info about devices support.

### Importance
This is the only react-three-fiber ecosystem webxr tool, and it looks very strange that this repository exists being partially working solution, without following it's original functional target?

**Comment by CodyJasonBennett** [comment]
The only actionable thing I can see here is adding a note about Apple's continued refusal to implement WebXR on iOS. I'm not going to entertain the rest.

**Comment by dendrofen** [comment]
Okey, good. 
And what about android, do we have any demo for android AR?

**Comment by CodyJasonBennett** [comment]
We don't have a posted demo yet for Android AR, but it would use `ARButton` as per the getting started example https://github.com/pmndrs/react-xr#getting-started.

```jsx
import { ARButton, XR } from '@react-three/xr'
import { Canvas } from '@react-three/fiber'

function App() {
  return (
    <>
      <ARButton />
      <Canvas>
        <XR>
          <mesh>
            <boxGeometry />
            <meshBasicMaterial color="blue" />
          </mesh>
        </XR>
      </Canvas>
    </>
  )
}
```
