### ISSUE TITLE
Set the viewer (camera) startposition in AR/VR 

### ISSUE THREAD

**Issue by chillbert** [pmndrs/xr#304]
Is there a way to set the camera position when AR session is starting? Preferably to the same as the non-AR session position. In this example I am setting the camera 2 units in front of the model (0,0,0) - in the non-AR session it looks good, as soon as I start the AR, the camera jumps to 0,0,0. 
```
 <XRButton
  mode={'AR'}
  sessionInit={{ optionalFeatures: ['local-floor'] }}
  enterOnly={false}
  exitOnly={false}
  onError={(error) => alert(JSON.stringify(error))}
>
  {(status) => `WebXR ${status}`}
</XRButton>
<Canvas shadows camera={{ position: [0,2,8], fov: 50 }} gl={{ logarithmicDepthBuffer: true, alpha:true }}>
    <XR>
      <Controllers />
      <Hands />
      <OrbitControls/>
      <fog attach="fog" args={["#d0d0d0", 20, 35]} />
      <ambientLight intensity={1} />
      <RayGrab>
        <XRBox />
      </RayGrab>
    </XR>
</Canvas>
```

**Comment by jjrchrds** [comment]
You can set the XR position with player, not sure yet how to just have it match the Canvas camera
```  const { player } = useXR();
  player.position.z = 5;
  ```

**Comment by chillbert** [comment]
Thanks, I didn't know useXR()... before I tried const { camera } = useThree(); but that is not available in VR/AR mode. 

Isn't useXR a hook that should refresh itself?

**Comment by chillbert** [comment]
Thanks, I didn't know useXR()... before I tried const { camera } = useThree(); but that is not available in VR/AR mode.

Isn't useXR a hook that should refresh itself? Since this is showing {"x":0,"y":0,"z":0} even when I (the player right? walk around...



`    
const { player } = useXR();
<Text color={"red"}>{JSON.stringify(player.position)}</Text>
`

**Comment by Pipe-Runner** [comment]
Hello @chillbert,
The player object represents the XR rig; the actual camera and controllers are children of this rig. These objects move relative to the rig when you move your HMD or controllers. When you teleport or use a joystick, you can move the rig itself so that everything moves together. To answer your question now, find the child object and get its position.

**Comment by vimal-hash** [comment]
Hi all – I’m learning React Three Fiber + react-three/xr and running into an issue with the built-in emulator:

I have a Man model and I’m using <XROrigin> to place the camera at its head.

In DevTools “Play Mode,” the XR session starts, but looking around with the emulator doesn’t rotate the Man model.

I don’t have a real headset, so I’m relying on the emulator only.


Has anyone gotten their avatar to follow head rotation under the emulator? Any tips or minimal code examples would be a huge help. Thanks!

**Comment by bbohlender** [comment]
@vimal-hash please do not add your issue into 2 places

**Comment by vimal-hash** [comment]
Yeah, I understood. Won't happen again.
