### ISSUE TITLE
Support for WebXR Depth Sensing?

### ISSUE THREAD

**Issue by Patrick-van-Halm-360Fabriek** [pmndrs/xr#309]
Will there be support for WebXR Depth Sensing, since currently there are issues with it? 

```js
toggleSession("immersive-ar", {
  sessionInit: {
    optionalFeatures: ["light-estimation", "depth-sensing"],
    requiredFeatures: ["hit-test", "local"],
    // @ts-ignore
    depthSensing: {
      usagePreference: ["cpu-optimized", "gpu-optimized"],
      dataFormatPreference: ["luminance-alpha", "float32"],
    },
  }
});
```

Causes an error as soon as the XR session is started. Within Three JS it seems like the XRManager:
```js
if ( enabledFeatures && enabledFeatures.includes( 'depth-sensing' ) ) {
  const depthData = glBinding.getDepthInformation( views[ 0 ] ); // Throws error since glBinding is null/undefined
  if ( depthData && depthData.isValid && depthData.texture ) {
    depthSensing.init( renderer, depthData, session.renderState );
  }
}
```

Depth Sensing has been added to Three JS since [r161](https://github.com/mrdoob/three.js/releases/tag/r161)

**Comment by MichaelLangbein** [comment]
Just stumbled over this issue. I'm still playing around with it, but I thought I'd share some links to further resources in case those are of use to anyone here.

I think there are two things going on here:
1. Threejs will only create `glBinding` if your device [also supports WebGR's `layers` module](https://github.com/mrdoob/three.js/blob/63fb5298a098ef3a78244a21892ec54db2876198/src/renderers/webxr/WebXRManager.js#L310). I'm not quite sure why; is there something about layers that is required for depth-sensing in threejs? There are [examples](https://webxr-depth.glitch.me/) of using depth-sensing without layers. One could consider including WebXR's [layers-polyfill](https://github.com/immersive-web/webxr-layers-polyfill/tree/main/build) but I didn't get much further with that.
2. Threejs assumes that your device [is using gpu-optimized depth-sensing](https://github.com/mrdoob/three.js/blob/63fb5298a098ef3a78244a21892ec54db2876198/src/renderers/webxr/WebXRManager.js#L777). The API for *cpu* optimized depth sensing would be [slightly different](https://github.com/immersive-web/depth-sensing/blob/main/explainer.md): there we'd use `const depthInfo = frame.getDepthInformation(views[0])`

I think it might be possible to create a CPU-equivalent of threejs'es current `WebXRDepthSensing` class. One would have to decide though what such a class should do: `WebXRDepthSensing` creates a new `Texture` with all data remaining on the CPU.
Should the CPU-equivalent upload its data to a texture on the GPU? That's probably bad for performance. Should it instead expose a different API-surface?

**Comment by bbohlender** [comment]
this has now an official API in react-three/xr v6.2
via `depthSensing: true` when creating a xr store
