### ISSUE TITLE
How to use arjs with react-xr ?

### ISSUE THREAD

**Issue by carllx** [pmndrs/xr#31]
I am learning to switch from A-frame to [RTF's Ecosystem](https://github.com/pmndrs/react-three-fiber#ecosystem). 
In `@react-three/xr` 's README.md, I found an [ar 's example](https://codesandbox.io/s/react-xr-simple-ar-demo-8w8hm), which is great. I believe that AR interaction is already a huge demand.It connects the real space and adds great value to the objects in the real space.
Now I hope to develop an AR app like Aframe to make some fun recognition behaviors, such as [Image Tracking](https://github.com/AR-js-org/AR.js#-image-tracking), [Location Based](https://github.com/AR-js-org/AR.js#location-based-example), [Marker Based](https://github.com/AR-js-org/AR.js#-marker-based-example), 
but in `@react-three/xr` I have not found any support or examples. Is anyone with similar development experience can give me some guidance here?  thank you~

**Comment by sniok** [comment]
So far this project only exposes existing three.js AR/VR features in a convenient way to use with react-three-fiber. I don't have that much knowledge about AR.js and how it works to give an opinion about this

**Comment by j-era** [comment]
Hey, we just released https://github.com/artcom/react-three-arjs. It's still in development, for now you can just try the marker based ar tracking. Because there is no npm module for ar.js available yet, we need to add it manually with webpack, have a look a the example. Hope this helps you for the beginning.

**Comment by timrijkse** [comment]
> Hey, we just released https://github.com/artcom/react-three-arjs. It's still in development, for now you can just try the marker based ar tracking. Because there is no npm module for ar.js available yet, we need to add it manually with webpack, have a look a the example. Hope this helps you for the beginning.

Cool stuff! Any plans to implement the Location based markers also?

**Comment by j-era** [comment]
> 

Hi @timrijkse, thank you! It is not planned yet, but when i find time i can take a look at how it could be integrated. If you like you can create an issue in  https://github.com/artcom/react-three-arjs. PR is also welcomed :)

**Comment by Carlos-AvilesBuitron** [comment]
@j-era I love your react-three-arjs project. Tracking is working great. Is there a way to add click handlers?
I have a cube mesh rendering but onClick does not work on it as it would with regular React Three Fiber.
Thanks for your great work.

**Comment by j-era** [comment]
> 

Thanks very much! I'll have a look at your issue.

**Comment by bbohlender** [comment]
To clarify, this library only uses WebXR as the underlying technology, so supporting alternatives such as AR.js are not in scope for this library. If WebXR does (yet) not provide the required features for your use case, I recommend looking at the aforementioned solutions, such as [react-three-arjs](https://github.com/artcom/react-three-arjs).

**Comment by coopbri** [comment]
Since `react-three-arjs` hasn't been committed to in years and was missing a bunch of use cases we decided to create an open-source (MIT) spiritual successor to it called Reality Development Kit (RDK): https://github.com/omnidotdev/rdk. We implemented fiducial marker-based AR with AR.js (leveraging R3F) and currently working on location-based AR.
