### ISSUE TITLE
`useHitTest` custom ray

### ISSUE THREAD

**Issue by abernier** [pmndrs/xr#313]
https://developer.mozilla.org/en-US/docs/Web/API/XRSession/requestHitTestSource#options accepts an optional `offsetRay: XRRay`

-> allow [current `useHitTest()` implementation](https://github.com/pmndrs/react-xr/blob/4d23eb88daa5ae484de05fa157cdc7fe366c2e47/src/Interactions.tsx#L272) to specify its own ray, like controllers' one for instance.

```js
// Assume raycaster is an instance of THREE.Raycaster

// Destructure the origin and direction vectors
const { origin, direction } = raycaster.ray;

// Normalize the direction vector
direction.normalize();

// Use object destructuring to directly pass the coordinates to the XRRay
const xrRay = new XRRay(
  { ...origin },  // Pass the x, y, z components of the origin
  { ...direction }  // Pass the x, y, z components of the normalized direction
);
```

**Comment by bbohlender** [comment]
the hit test api in 6.1 supports rays originating from any position :)

**Comment by abernier** [comment]
I can't even remember why I needed this :D but the fact you implemented it is awesome, congrats @bbohlender
