### ISSUE TITLE
Enable http with a flag

### ISSUE THREAD

**Issue by 99Arrzel** [pmndrs/xr#315]
in XR.tsx allow the isHttps flag to be ignored, this could help to work this in development mode.
`const isHttps = location.protocol === 'https:'`

**Comment by bbohlender** [comment]
WebXR can only be used with https per spec.
> Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API#browser_compatibility).
