### ISSUE TITLE
pointer-events forwardObjectEvents inverted

### ISSUE THREAD

**Issue by Ledzz** [pmndrs/xr#318]
The forwardObjectEvents function in @pmndrs/pointer-events is inverted in y axis.
Here's repro, try hovering on blue rectangles:
https://stackblitz.com/edit/vitejs-vite-wdmsfi?file=src%2Fmain.tsx

I fixed it locally by removing [this line](https://github.com/pmndrs/xr/blob/main/packages/pointer-events/src/forward.ts#L67), and I can make a PR with this fixed, I just wanted to ask, was there a specific reason to do it that way, or is it just a mistake?

**Comment by bbohlender** [comment]
Thanks for catching that (my current test setup was symmetrical on the y axis so i did not catch that). I already fixed it, but you can also make a PR, if you want to get listed for fixing it ;-)
Will release a version with the fix tomorrow

**Comment by Ledzz** [comment]
Oh I'm not haunting for popularity, but appreciate the offer :)
I'll better wait for fix, thank you!

**Comment by bbohlender** [comment]
fixed in 6.1 :)
sorry for the delay
