### ISSUE TITLE
Cannot work with Immersive Web Emulator, while previous versions can

### ISSUE THREAD

**Issue by kencheung0804** [pmndrs/xr#319]
In previous versions, I could use Immersive web emulator to debug. But after using new versions, and the store.enterVR() does not lead me to a VR view in the browser with the emulator. 

Of course, using a real VR device works fine. But the debugging is hard. Did I do anything wrong??

**Comment by bbohlender** [comment]
Unfortunately the current immersive web emulator uses the old emulation runtime that only partially implements the WebXR spec. The new version is using some features that are not supported and I decided to not implement those things how they are ment to be implemented regarding the WebXR standard, which is not supported by the current runtime.

Fortunately the meta team was already aware of this and worked on a completely new and improved immersive web emulation runtime https://developer.oculus.com/blog/immersive-web-emulation-runtime-iwer-webxr-meta-quest-developer/

So its only a matter of time until a new emulator is there.

**Comment by bbohlender** [comment]
I will close this issue once a new supported emulator build on the new IWER is out :)

**Comment by kencheung0804** [comment]
Thanks. Closing after new support would be great.

Another quesion about debugging. 

I am trying out some simplified version of the examples in the project like below. It was found that even in oculus browser, the VR permssion box and VR screen did not show up as previous versions after pressing the VR button during debug in local network. But the examples in the document worked just fine. 

Again, is it the same problem as the IWER or did I just do something wrong?

```
import { MutableRefObject, useRef } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { SoftShadows, Float, CameraControls, Sky } from '@react-three/drei';
import { easing } from 'maath';
import { XR, XROrigin, createXRStore } from '@react-three/xr';
import { Group, Object3DEventMap, Vector3 } from 'three';

function Light() {
  const ref = useRef() as MutableRefObject<Group<Object3DEventMap>>;
  useFrame((state, delta) => {
    easing.dampE(
      ref.current.rotation,
      [(state.pointer.y * Math.PI) / 50, (state.pointer.x * Math.PI) / 20, 0],
      0.2,
      delta
    );
  });
  return (
    <group ref={ref}>
      <directionalLight
        position={[5, 5, -8]}
        castShadow
        intensity={5}
        shadow-mapSize={2048}
        shadow-bias={-0.001}
      >
        <orthographicCamera
          attach="shadow-camera"
          args={[-8.5, 8.5, 8.5, -8.5, 0.1, 20]}
        />
      </directionalLight>
    </group>
  );
}

const store = createXRStore();

export default function App() {
  return (
    <>
      <button
        style={{
          position: 'absolute',
          zIndex: 10000,
          background: 'black',
          borderRadius: '0.5rem',
          border: 'none',
          fontWeight: 'bold',
          color: 'white',
          padding: '1rem 2rem',
          cursor: 'pointer',
          fontSize: '1.5rem',
          bottom: '1rem',
          left: '50%',
          boxShadow: '0px 0px 20px rgba(0,0,0,1)',
          transform: 'translate(-50%, 0)',
        }}
        onClick={() => store.enterVR()}
      >
        Enter VR
      </button>
      <Canvas shadows camera={{ position: [5, 2, 10], fov: 50 }}>
        <XR store={store}>
          <SoftShadows />
          <CameraControls makeDefault />
          <color attach="background" args={['#d0d0d0']} />
          <fog attach="fog" args={['#d0d0d0', 8, 35]} />
          <ambientLight intensity={0.4} />
          <Light />

          <Sphere />
          <Sphere position={new Vector3(2, 4, -8)} scale={0.9} />
          <Sphere position={new Vector3(-2, 2, -8)} scale={0.8} />
          <Sky inclination={0.52} />
          <XROrigin scale={2} position={[-3.5, -1.85, 3.5]} />
        </XR>
      </Canvas>
    </>
  );
}

function Sphere({
  color = 'hotpink',
  floatIntensity = 15,
  position = new Vector3(0, 5, 8),
  scale = 1,
}) {
  return (
    <Float floatIntensity={floatIntensity}>
      <mesh castShadow position={position} scale={scale}>
        <sphereGeometry />
        <meshBasicMaterial color={color} />
      </mesh>
    </Float>
  );
}
```

**Comment by bbohlender** [comment]
The code looks correct.
Make sure that you are using https

If that still does not work, use adb to open up the chrome inspector on your PC, and check for errors.
If there are not errors, maybe you can give me access to your repo, and I can check myself.

Some further information about your device might be helpful :)

**Comment by bbohlender** [comment]
6.1 is now released with default emulator ([iwer/devui](https://github.com/meta-quest/immersive-web-emulation-runtime/tree/main/devui)) integration
Make sure to disable the IWE and WebXR API emulator to use this.
It is automaitcally enabled on localhost and can be enabled everywhere else where WebXR is not supported via `windows/command + alt/options + e`
