### ISSUE TITLE
When using `@iwer/devui`, the mode is always `immersive-ar`

### ISSUE THREAD

**Issue by kwaa** [pmndrs/xr#320]
I'm unsure what it's because of, but here's a minimal repro: https://stackblitz.com/edit/vitejs-vite-zfgehf

Press <kbd>Win</kbd> + <kbd>Alt</kbd> + <kbd>E</kbd> and press the "Enter VR" button, the console print `store.getState().mode` is now `immersive-ar` and displays the "AR" text

my debug code:

```ts
const enterXRDebug = (
  store: XRStore,
  mode: 'immersive-ar' | 'immersive-vr'
) => {
  store.enterXR(mode);
  setTimeout(() => console.log(store.getState().mode), 1000);
};
```

```tsx
<IfInSessionMode allow="immersive-ar">
  <Text>AR</Text>
</IfInSessionMode>
<IfInSessionMode allow="immersive-vr">
  <Text>VR</Text>
</IfInSessionMode>
```

**Comment by bbohlender** [comment]
@kwaa thanks for reporting
this now works as expected in iwer 1.0.4 thanks to @felixtrz
