### ISSUE TITLE
How to use it on an Android device's browser? Nothing happens after clicking the start button

### ISSUE THREAD

**Issue by Signinu** [pmndrs/xr#338]
![image](https://github.com/user-attachments/assets/440457a3-60cc-4f8c-8cd3-eca0f411ae12)
Nothing happens after clicking this button

**Comment by Signinu** [comment]
Chrome browser I use

**Comment by bbohlender** [comment]
it seems like your browser does not support WebXR, which is why the emulator starts up.
To better understand your issue, I need more information. I also recommend checking out the [pitfalls](https://pmndrs.github.io/xr/docs/advanced/pitfalls) to assure your not running in any of those issue (e.g. missing https).

**Comment by Signinu** [comment]
Please tell me a browser that can use XR projects on Android phones. Thank you very much. My project needs to run on Android phones.

**Comment by Signinu** [comment]
This is the browser version I'm using now
![20240822-101323](https://github.com/user-attachments/assets/2d42d5eb-e140-4278-bc6b-7d7058d143c2)

**Comment by Signinu** [comment]
![20240822-165517](https://github.com/user-attachments/assets/367ae52c-c945-4516-ba33-788c2c9043d4)
If it is normal, what will happen when I click this button? Currently, there is no response when I click this button

**Comment by bbohlender** [comment]
The button is for emulation on a computer with mouse and keyboard.
Make sure your device has the required services installed to run AR things. If I remember correctly you need some google play services for android.

**Comment by Signinu** [comment]
Yes, I have installed Google Play Services for AR, version 1.43+, but I still don't know how to enter AR mode with Chrome browser

**Comment by Signinu** [comment]
When I enter the webpage, there is no pop-up button to enter AR mode

**Comment by Signinu** [comment]
Thank you very much. After commenting out the code in the simulator, you can enter AR mode normally.

**Comment by bbohlender** [comment]
@Signinu Could you explain what "commenting out the code in the simular" means. Since, if you actually had to modify the source code to make it run, this sounds like a bug that should be fixed :)
