### ISSUE TITLE
OnDemand Grab Pointer

### ISSUE THREAD

**Issue by WawasCode** [pmndrs/xr#356]
This is the current behavior with the default `createXRStore` setup:
Imagine following scenario where we have a sphere and behind it a plane.
<img width="765" alt="image" src="https://github.com/user-attachments/assets/66753bf9-4872-439a-b958-77821a7df3d4">

If I point the Ray at the plane the target will be on it.
<img width="757" alt="image" src="https://github.com/user-attachments/assets/7d4a0ad3-b3d5-492d-9f02-0030ee3c36bc">
Once we move close enough we enable the grab pointer.

<img width="634" alt="image" src="https://github.com/user-attachments/assets/672d82a2-f809-4467-b3eb-0387c96c21a5">
My issue is shown in the image above. If the ray is targeting something else and I move the controller close enough to the sphere that I should be able to trigger the grab, I can’t click on it because the ray is still active.

Would it be possible to have a sphere around the controller/hands that checks for intersections with objects? If so, could it switch to grab mode when an intersection is detected?

What are your thoughts on that?

**Comment by bbohlender** [comment]
exactly what you describe is already the case. You can modify the hover radius of the controller to make the intersection with the sphere happen earlier. Feel free to reopen if the behavior is not what you expect
