### ISSUE TITLE
Test example on Ipad

### ISSUE THREAD

**Issue by RyugaRyuzaki** [pmndrs/xr#358]
Hi guys, does anyone know how can i test https://github.com/pmndrs/xr/tree/main/examples in my ipad?Many thank

**Comment by bbohlender** [comment]
@RyugaRyuzaki as you can read in the docs. IOs devices do not support WebXR in their browsers currently (https://pmndrs.github.io/xr/docs/getting-started/faq#does-it-work-on-ios?).

Fortunately there are solutions:
https://play.eyejack.xyz/
https://launch.variant3d.com/
