### ISSUE TITLE
Meta Immersive Web Emulator is not working with XR

### ISSUE THREAD

**Issue by fsereno** [pmndrs/xr#362]
Hi there,

I can't seem to get the Immersive Web Emulator from Meta to work with my XR project using [pmndrs.github.io/xr/docs/](https://pmndrs.github.io/xr/docs/)

Do I need to enable anything ?

Chrome, on Windows and Mac.

Many thanks

**Comment by bbohlender** [comment]
Hey :)
yes that is currently expected, you can read about it and the correct solution here:
https://pmndrs.github.io/xr/docs/getting-started/development-setup
