### ISSUE TITLE
Render HTML on XR Immersive Scene

### ISSUE THREAD

**Issue by rifkyariy** [pmndrs/xr#366]
I'm currently developing an XR application using @react-three/drei and @react-three/xr in React Three Fiber and need to display HTML content, specifically a Chart.js line chart, within the XR scene. I attempted using Html from @react-three/drei for overlay, but the element doesn’t appear when the app is in XR mode but appear on browser.

![167543acea904a64b74d9d738df5c1f7](https://github.com/user-attachments/assets/e5828873-d52c-4b12-8aed-14e25ee85983)
![4708a36cfd0f4c07aa367e4310225910](https://github.com/user-attachments/assets/9630e3e5-7485-4d5f-a88d-9a4585dd85e6)
![7c04a4736bfa432ab3e8efabdd4c32d3](https://github.com/user-attachments/assets/035a9cd4-6d53-4eef-801d-d7ca49db482a)

**Comment by bbohlender** [comment]
Html content cannot be displayed in WebXR
https://pmndrs.github.io/xr/docs/getting-started/faq#how-can-i-put-html-in-my-xr-scene?

For this use case, I would recommend generating the charts with SVG using then rendering the generated SVG on a texture

**Comment by rifkyariy** [comment]
When I generate an SVG and load it into drei/Svg, the text tag doesn’t render in XR mode, nor does it appear in the 3D scene. I noticed that the pmndrs/uikit has a similar component that does render in XR mode, but it’s only a bar chart (link: https://github.com/pmndrs/uikit/blob/main/examples/dashboard/src/components/Overview.tsx).

My goal is to create a line or pie chart. Are there any third-party libraries I can use to achieve this?
