### ISSUE TITLE
Errors in the base example in README.md

### ISSUE THREAD

**Issue by mrosati84** [pmndrs/xr#380]
hi,
right off the bat when copying and pasting the example in the README results in an error.

- `export function App()` should perhaps be `export default function App()` otherwise the example does not run
- `<meshBasicMaterial color={red ? 'red' : 'blue'} />` VSCode warns about the `color` option with the following error

Please note that the second does not block the page from running (the first does), but still the error in VSCode remains.

```
Type '{ color: string; }' is not assignable to type 'ExtendedColors<Overwrite<Partial<{}>, NodeProps<{}, {}>>>'.
  Property 'color' does not exist on type 'ExtendedColors<Overwrite<Partial<{}>, NodeProps<{}, {}>>>'.ts(2322)
```

**Comment by mrosati84** [comment]
For reference, I am running the example in an empty React project initialized using Vite (TS template).

**Comment by bbohlender** [comment]
These errors are all related to the template and not to the example. Your template consumes the App as the default export, but that's just a decision of the template author, other users using other templates might have different imports for the default App. In general default exports are discouraged. The type error is related the local typescript version and the tsconfig.

I'll keep in mind that we need to add a R3F+XR template soon but there are other more pressing issues (docs rewrite) atm
